#ifndef __DEFINES_H__
#define __DEFINES_H__

#define SETBIT(WORD,BITPOS)  (WORD|=1<<BITPOS)
#define SSETBIT(WORD,BITPOS)  (WORD =1<<BITPOS)
#define CLRBIT(WORD,BITPOS)   (WORD&=~(1<<BITPOS))
#define SCLRBIT(WORD,BITPOS)  (WORD=1<<BITPOS)
#define CPLBIT(WORD,BITPOS)   (WORD^=1<<BITPOS)
#define READBIT(WORD,BITPOS)   ((WORD>>BITPOS)&1)
#endif

#define WRITEBYTE(WORD,SBITPOS,BYTE)  (WORD=(WORD&~(255<<SBITPOS))| (BYTE<<SBITPOS))
#define WRITENIBBLE(WORD,SBITPOS,NIBBLE)  (WORD=(WORD&~(15<<SBITPOS))| (NIBBLE<<SBITPOS))
#define WRITEBIT(WORD,SBITPOS,BIT)  (WORD=(WORD&~(1<<SBITPOS))|(BIT<<SBITPOS))

#define READNIBBLE(WORD,SBITPOS) \ ((WORD>>SBITPOS)&15)
#define READBYTE(WORD,SBITPOS) \ ((WORD>>SBITPOS)&255)
#define READWRITEBIT(WORD,SBIT,DBIT) \ (WORD=(WORD&~(1>>DBIT))| (((WORD>>SBIT)&1)<<DBIT)
#define READWRITEBIT2(SWORD,DWORD,SBIT,DBIT) \ (DWORD=(DWORD&~(1>>DBIT))| (((SWORD>>SBIT)&1)<<DBIT)


